#!/usr/bin/env python3
"""Buchholz.lean (PSS → Buchholz 項) の照合テスト生成。

参照実装（naruyoko 氏 common.js の Trans を呼び `M => D_0 …` 形式で出力する Node
スクリプト。環境変数 BUCHHOLZ_REF_JS で指定）の出力を正とし、#guard 行を
lean/tests/BuchholzTestInline.lean
（Buchholz.lean の全文 + #guard 行、単独で leanman check できる）に書き出す。
"""
import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PSS2BP = os.environ.get('BUCHHOLZ_REF_JS', 'buchholz_ref.js')
CLI = os.path.join(ROOT, 'lean', '.lake', 'build', 'bin', 'bms2tc')
SRC = os.path.join(ROOT, 'lean', 'BmsTc', 'Buchholz.lean')
OUT = os.path.join(ROOT, 'lean', 'tests', 'BuchholzTestInline.lean')


def nrows(m):
    return m.split(')')[0].count(',') + 1 if m.startswith('(') else 0


def expand(m, n):
    p = subprocess.run([CLI, 'bms-expand', f'{m}[{n}]'], capture_output=True, text=True)
    return p.stdout.strip()


def main():
    rows = json.load(open(os.path.join(ROOT, 'sheet', 'bms_rows.json')))
    mats = []
    seen = set()
    def add(m):
        if m and m not in seen and len(m) < 700:
            seen.add(m); mats.append(m)
    for _, b, _ in rows:
        if nrows(b) == 2:
            add(b)
    seeds = ['(0,0)(1,1)(2,2)', '(0,0)(1,1)(2,2)(3,3)', '(0,0)(1,1)(2,1)(3,2)', '(0,0)(1,1)(2,2)(3,2)']
    # xlsx の 2 行行列も 1 段展開してテストに加える
    for m in list(mats):
        for n in (1, 2):
            add(expand(m, n))
    frontier = list(seeds)
    for m in seeds: add(m)
    for _ in range(4):
        nxt = []
        for m in frontier:
            for n in (1, 2, 3):
                e = expand(m, n)
                if e and e not in seen and len(e) < 700:
                    add(e); nxt.append(e)
        frontier = nxt
    p = subprocess.run(['node', PSS2BP, '--raw'], input='\n'.join(mats) + '\n', capture_output=True, text=True)
    ref = {}
    for line in p.stdout.splitlines():
        if '=>' in line:
            a, b = line.split('=>')
            ref[a.strip()] = b.strip()
    src = open(SRC).read()
    lines = [src, '', '-- generated by tools/gen_buchholz_tests.py; reference: naruyoko common.js Trans (raw output)', '']
    n = 0
    for m in mats:
        if m in ref:
            lines.append(f'#guard Buchholz.transStr "{m}" == some "{ref[m]}"')
            n += 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write('\n'.join(lines) + '\n')
    print(f'{n} cases (of {len(mats)} matrices; reference failed on {len(mats) - n}) -> {OUT}')


if __name__ == '__main__':
    main()
