#!/usr/bin/env python3
"""Generate #guard tests for lean/BmsTc/Bms.lean from the yaBMS C binary.

    tools/gen_bms_tests.py            # writes lean/tests/BmsTest.lean (imports BmsTc.Bms)
    tools/gen_bms_tests.py --inline   # writes lean/tests/BmsTestInline.lean (self-contained)
    tools/gen_bms_tests.py --pycheck  # only cross-check tools/bms_ref.py against ./bms

Test matrices: expansions of the diagonals (0)(1)(2), (0,0)(1,1)(2,2),
(0,0,0)(1,1,1)(2,2,2) with brackets 1..3 (standard), plus random matrices
(mostly non-standard).  Oracle: ./bms -v4 (expand), -s (standard), -c (compare).
"""
import os
import random
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BMS = os.environ.get('YABMS_BMS', 'bms')  # yaBMS (github.com/koteitan/yaBMS) の c/bms
sys.path.insert(0, HERE)
import bms_ref as ref  # noqa: E402


def run(args):
    return subprocess.run([BMS] + args, capture_output=True, text=True).stdout.strip()


def c_expand(s, b):
    return run(['-v4', f'{s}[{b}]'])


def c_std(s):
    return run(['-s', s]) == '1'


def c_cmp(a, b):
    return int(run(['-c', a, b]))


def gen_matrices(seed=20260913):
    rnd = random.Random(seed)
    mats = set()
    diags = ['(0)(1)(2)', '(0,0)(1,1)(2,2)', '(0,0,0)(1,1,1)(2,2,2)',
             '(0)(1)(2)(3)', '(0,0)(1,1)(2,2)(3,3)', '(0,0,0)(1,1,1)(2,2,1)']
    frontier = list(diags)
    mats.update(diags)
    for _ in range(600):
        s = rnd.choice(frontier)
        m, _ = ref.parse(s)
        if len(m) == 0:
            continue
        b = rnd.randint(1, 3)
        e = ref.expand(m, b)
        t = ref.tostr(e)
        if 1 <= len(e) <= 9 and len(t) < 200:
            mats.add(t)
            frontier.append(t)
    # random (mostly non-standard) matrices
    for _ in range(150):
        ys = rnd.randint(1, 3)
        xs = rnd.randint(2, 6)
        cols = [[rnd.randint(0, min(x, 3)) for _ in range(ys)] for x in range(xs)]
        cols[0] = [0] * ys
        mats.add(ref.tostr(cols))
    return sorted(mats, key=lambda s: (len(s), s))


def build_cases(mats, rnd):
    cases = []  # (kind, a, b, result)
    for s in mats:
        m, _ = ref.parse(s)
        std = c_std(s)
        cases.append(('std', s, None, std))
        if std:
            for b in (1, 2, 3):
                e = c_expand(s, b)
                if len(e) < 400:
                    cases.append(('exp', s, b, e))
    for _ in range(120):
        a, b = rnd.sample(mats, 2)
        ma, _ = ref.parse(a)
        mb, _ = ref.parse(b)
        if len(ma[0]) != len(mb[0]):
            continue
        cases.append(('cmp', a, b, c_cmp(a, b)))
    return cases


def pycheck(cases):
    bad = 0
    for kind, a, b, res in cases:
        m, _ = ref.parse(a)
        if kind == 'std':
            got = ref.is_standard(m)
        elif kind == 'exp':
            got = ref.tostr(ref.expand(m, b))
        else:
            got = ref.compare(m, ref.parse(b)[0])
        if got != res:
            bad += 1
            print('MISMATCH', kind, a, b, 'c=', res, 'py=', got)
    print(f'{len(cases)} cases, {bad} mismatches')
    return bad


def lean_lines(cases):
    out = []
    ordmap = {1: '.gt', 0: '.eq', -1: '.lt'}
    for kind, a, b, res in cases:
        if kind == 'std':
            out.append(f'#guard Bms.isStandard (Bms.parse! "{a}") == {"true" if res else "false"}')
        elif kind == 'exp':
            out.append(f'#guard Bms.toString (Bms.expand (Bms.parse! "{a}") {b}) == "{res}"')
        else:
            out.append(f'#guard Bms.compare (Bms.parse! "{a}") (Bms.parse! "{b}") == {ordmap[res]}')
    return out


def main():
    if not os.path.exists(BMS):
        subprocess.run(['make', '-C', os.path.dirname(BMS)], check=True)
    rnd = random.Random(1)
    mats = gen_matrices()
    cases = build_cases(mats, rnd)
    if '--pycheck' in sys.argv:
        sys.exit(1 if pycheck(cases) else 0)
    lines = lean_lines(cases)
    tests_dir = os.path.join(ROOT, 'lean', 'tests')
    os.makedirs(tests_dir, exist_ok=True)
    header = f'-- generated by tools/gen_bms_tests.py from yaBMS ./bms ({len(cases)} cases)\n'
    if '--inline' in sys.argv:
        src = open(os.path.join(ROOT, 'lean', 'BmsTc', 'Bms.lean')).read()
        path = os.path.join(tests_dir, 'BmsTestInline.lean')
        open(path, 'w').write(src + '\n' + header + '\n'.join(lines) + '\n')
    else:
        path = os.path.join(tests_dir, 'BmsTest.lean')
        open(path, 'w').write('import BmsTc.Bms\n' + header + '\n'.join(lines) + '\n')
    print(f'wrote {path}: {len(cases)} cases')


if __name__ == '__main__':
    main()
