import BmsTc.Bms
-- generated by tools/gen_bms_tests.py from yaBMS ./bms (654 cases)
#guard Bms.isStandard (Bms.parse! "(0)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)") 1) == "(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)") 2) == "(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)") 3) == "(0)"
#guard Bms.isStandard (Bms.parse! "(0)(1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)") 1) == "(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)") 2) == "(0)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)") 3) == "(0)(0)(0)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(0)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)(0)") 1) == "(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)(0)") 2) == "(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)(0)") 3) == "(0)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(0)(1)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(2)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)") 1) == "(0)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)") 2) == "(0)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)") 3) == "(0)(1)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)") 1) == "(0)(1)(0)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)") 2) == "(0)(1)(0)(1)(0)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)") 3) == "(0)(1)(0)(1)(0)(1)(0)(1)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)") 1) == "(0)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)") 2) == "(0)(1)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)") 3) == "(0)(1)(1)(1)(1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(0,0)") 1) == "(0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(0,0)") 2) == "(0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(0,0)") 3) == "(0,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,0)") 1) == "(0,0)(0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,0)") 2) == "(0,0)(0,0)(0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,0)") 3) == "(0,0)(0,0)(0,0)(0,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)") 1) == "(0,0)(1,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)") 2) == "(0,0)(1,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)") 3) == "(0,0)(1,0)(2,0)(3,0)"
#guard Bms.isStandard (Bms.parse! "(0)(0)(0)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)(0)(0)") 1) == "(0)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)(0)(0)") 2) == "(0)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(0)(0)(0)") 3) == "(0)(0)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(0)(1)(0)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(2)(0)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(2)(1)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)") 1) == "(0)(1)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)") 2) == "(0)(1)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)") 3) == "(0)(1)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)") 1) == "(0)(1)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)") 2) == "(0)(1)(0)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)") 3) == "(0)(1)(0)(0)(0)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(2)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(1)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(0)") 1) == "(0)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(0)") 2) == "(0)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(0)") 3) == "(0)(1)(1)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(1)(1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)") 1) == "(0)(1)(1)(0)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)") 2) == "(0)(1)(1)(0)(1)(1)(0)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)") 3) == "(0)(1)(1)(0)(1)(1)(0)(1)(1)(0)(1)(1)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(2)(3)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(3)") 1) == "(0)(1)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(3)") 2) == "(0)(1)(2)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(3)") 3) == "(0)(1)(2)(2)(2)(2)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(0,0,0)") 1) == "(0,0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(0,0,0)") 2) == "(0,0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(0,0,0)") 3) == "(0,0,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,0,0)") 1) == "(0,0,0)(0,0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,0,0)") 2) == "(0,0,0)(0,0,0)(0,0,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,0,0)") 3) == "(0,0,0)(0,0,0)(0,0,0)(0,0,0)"
#guard Bms.isStandard (Bms.parse! "(0)(0)(0)(1)(2)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(0)(1)(3)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(1)(2)(1)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(1)(3)(1)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(0)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)(0)") 1) == "(0)(1)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)(0)") 2) == "(0)(1)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)(0)") 3) == "(0)(1)(0)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(0)(1)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(1)(1)(1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)(1)") 1) == "(0)(1)(1)(1)(0)(1)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)(1)") 2) == "(0)(1)(1)(1)(0)(1)(1)(1)(0)(1)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)(1)") 3) == "(0)(1)(1)(1)(0)(1)(1)(1)(0)(1)(1)(1)(0)(1)(1)(1)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(1)(2)(2)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(2)(2)(2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)") 1) == "(0)(1)(2)(2)(1)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)") 2) == "(0)(1)(2)(2)(1)(2)(2)(1)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)") 3) == "(0)(1)(2)(2)(1)(2)(2)(1)(2)(2)(1)(2)(2)"
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(0,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(0,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)") 1) == "(0,0)(1,1)(2,0)(3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)") 1) == "(0,0)(1,1)(2,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)") 2) == "(0,0)(1,1)(2,1)(3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)") 3) == "(0,0)(1,1)(2,1)(3,1)(4,1)"
#guard Bms.isStandard (Bms.parse! "(0)(0)(0)(0)(0)(1)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(1)(2)(0)(1)") == false
#guard Bms.isStandard (Bms.parse! "(0)(0)(2)(3)(3)(0)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(0)(0)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)(0)(0)") 1) == "(0)(1)(0)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)(0)(0)") 2) == "(0)(1)(0)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(0)(0)(0)") 3) == "(0)(1)(0)(0)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(2)(2)(0)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(3)(0)(2)") == false
#guard Bms.isStandard (Bms.parse! "(0)(1)(2)(2)(2)(2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)(2)") 1) == "(0)(1)(2)(2)(2)(1)(2)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)(2)") 2) == "(0)(1)(2)(2)(2)(1)(2)(2)(2)(1)(2)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)(2)") 3) == "(0)(1)(2)(2)(2)(1)(2)(2)(2)(1)(2)(2)(2)(1)(2)(2)(2)"
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,2)(0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,2)(1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,2)(2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(0,1)(0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(1,2)(0,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(1,2)(2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(2,1)(1,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,0)(2,0)(0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(0,0)(0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(0,2)(2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(1,0)(1,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)") 1) == "(0,0)(1,1)(2,0)(1,1)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)") 2) == "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)") 3) == "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)") 1) == "(0,0)(1,1)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)") 2) == "(0,0)(1,1)(2,0)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)") 3) == "(0,0)(1,1)(2,0)(2,0)(2,0)(2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)") 1) == "(0,0)(1,1)(2,0)(3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)") 2) == "(0,0)(1,1)(2,0)(3,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)") 3) == "(0,0)(1,1)(2,0)(3,0)(4,0)(5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,1)(3,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)") 1) == "(0,0)(1,1)(2,1)(3,0)(4,1)(5,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)") 2) == "(0,0)(1,1)(2,1)(3,0)(4,1)(5,1)(6,0)(7,1)(8,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)") 3) == "(0,0)(1,1)(2,1)(3,0)(4,1)(5,1)(6,0)(7,1)(8,1)(9,0)(10,1)(11,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,2)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,3)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,3)") 1) == "(0,0)(1,1)(2,2)(3,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,3)") 2) == "(0,0)(1,1)(2,2)(3,2)(4,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,3)") 3) == "(0,0)(1,1)(2,2)(3,2)(4,2)(5,2)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(2)(2)(1)(2)(2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(1)(2)(2)") 1) == "(0)(1)(2)(2)(1)(2)(1)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(1)(2)(2)") 2) == "(0)(1)(2)(2)(1)(2)(1)(2)(1)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(1)(2)(2)") 3) == "(0)(1)(2)(2)(1)(2)(1)(2)(1)(2)(1)(2)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(1,0,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(1,1,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,1)(0,1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,1)(2,0,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,1)(2,1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(0,2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,1)(0,0,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,1)(2,2,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,0)(0,0,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,1)(0,2,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,1)(1,0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,1)(1,0,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(0,0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(2,1,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(0,2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,1)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,2)") 1) == "(0,0,0)(1,1,1)(2,2,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,2)") 2) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,2)") 3) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,1)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(0)") 1) == "(0)(1)(0)(1)(0)(1)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(0)") 2) == "(0)(1)(0)(1)(0)(1)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(0)") 3) == "(0)(1)(0)(1)(0)(1)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(1)") 1) == "(0)(1)(0)(1)(0)(1)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(1)") 2) == "(0)(1)(0)(1)(0)(1)(0)(0)(0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(0)(1)(0)(1)(0)(1)") 3) == "(0)(1)(0)(1)(0)(1)(0)(0)(0)(0)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(1)(1)(0)(1)(1)(1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)(0)(1)(1)(1)") 1) == "(0)(1)(1)(1)(0)(1)(1)(0)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)(0)(1)(1)(1)") 2) == "(0)(1)(1)(1)(0)(1)(1)(0)(1)(1)(0)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(1)(1)(0)(1)(1)(1)") 3) == "(0)(1)(1)(1)(0)(1)(1)(0)(1)(1)(0)(1)(1)(0)(1)(1)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(2)(2)(1)(2)(1)(2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(1)(2)(1)(2)") 1) == "(0)(1)(2)(2)(1)(2)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(1)(2)(1)(2)") 2) == "(0)(1)(2)(2)(1)(2)(1)(1)(1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(1)(2)(1)(2)") 3) == "(0)(1)(2)(2)(1)(2)(1)(1)(1)(1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(0,0)(1,0)(1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(0,0)(1,0)(1,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(0,1)(3,0)(2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,2)(3,3)(2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(2,1)(3,0)(2,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(1,2)(1,1)(3,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,0)(2,0)(0,3)(1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(0,1)(1,0)(3,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)") 1) == "(0,0)(1,1)(2,0)(1,1)(1,0)(2,1)(3,0)(2,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)") 2) == "(0,0)(1,1)(2,0)(1,1)(1,0)(2,1)(3,0)(2,1)(2,0)(3,1)(4,0)(3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)") 3) == "(0,0)(1,1)(2,0)(1,1)(1,0)(2,1)(3,0)(2,1)(2,0)(3,1)(4,0)(3,1)(3,0)(4,1)(5,0)(4,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)") 1) == "(0,0)(1,1)(2,0)(1,1)(1,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)") 2) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)") 3) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)") 1) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)") 2) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)") 3) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)") 1) == "(0,0)(1,1)(2,0)(3,0)(3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)") 2) == "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)") 3) == "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(3,0)") 1) == "(0,0)(1,1)(2,1)(3,1)(2,1)(3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(3,0)") 2) == "(0,0)(1,1)(2,1)(3,1)(2,1)(3,1)(2,1)(3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(3,0)") 3) == "(0,0)(1,1)(2,1)(3,1)(2,1)(3,1)(2,1)(3,1)(2,1)(3,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,1)") 1) == "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,1)") 2) == "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,1)(8,0)(9,1)(10,1)(11,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,1)") 3) == "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,1)(8,0)(9,1)(10,1)(11,1)(12,0)(13,1)(14,1)(15,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,1)(8,0)(9,1)(10,2)(11,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,1)(8,0)(9,1)(10,2)(11,1)(12,0)(13,1)(14,2)(15,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)") 1) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)") 2) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)(7,1)(8,2)(9,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)") 3) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)(7,1)(8,2)(9,2)(10,1)(11,2)(12,2)"
#guard Bms.isStandard (Bms.parse! "(0)(1)(2)(2)(2)(1)(2)(2)(2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)(1)(2)(2)(2)") 1) == "(0)(1)(2)(2)(2)(1)(2)(2)(1)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)(1)(2)(2)(2)") 2) == "(0)(1)(2)(2)(2)(1)(2)(2)(1)(2)(2)(1)(2)(2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0)(1)(2)(2)(2)(1)(2)(2)(2)") 3) == "(0)(1)(2)(2)(2)(1)(2)(2)(1)(2)(2)(1)(2)(2)(1)(2)(2)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(0,2,1)(0,2,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(1,2,2)(1,0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,1)(0,0,2)(0,0,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(0,0,0)(1,2,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(1,0,2)(3,2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(1,1,0)(3,3,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,1)(2,1,2)(2,2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(0,0,2)(2,3,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(1,2,1)(0,0,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(2,2,1)(3,0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(2,2,2)(0,3,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)") 1) == "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)") 2) == "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)") 3) == "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,1)(9,9,0)(10,10,1)(11,11,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,2)(1,0)(1,0)(2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,0)(1,2)(3,1)(2,3)(3,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(0,0)(1,1)(1,0)(2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(0,1)(2,1)(2,3)(1,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(1,2)(2,1)(1,1)(0,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(0,1)(2,1)(2,1)(2,3)(0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,0)(0,0)(1,0)(2,0)(2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,0)(1,1)(3,0)(0,3)(2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,0)(1,2)(1,3)(0,1)(3,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,0)(2,2)(0,1)(1,1)(3,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(1,0)(0,2)(1,0)(3,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(0,3)(1,1)(0,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)") 1) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,0)(2,1)(3,0)(2,1)(2,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)") 2) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,0)(2,1)(3,0)(2,1)(2,1)(2,0)(3,1)(4,0)(3,1)(3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)") 3) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,0)(2,1)(3,0)(2,1)(2,1)(2,0)(3,1)(4,0)(3,1)(3,1)(3,0)(4,1)(5,0)(4,1)(4,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(2,0)") 1) == "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(2,0)") 2) == "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(2,0)") 3) == "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(5,0)") 1) == "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(5,0)") 2) == "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(5,0)") 3) == "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(3,1)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(3,1)(4,0)(3,1)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(3,1)(4,0)(3,1)(4,0)(3,1)(4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(7,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,1)(3,2)(0,1)(3,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,0)(6,1)(7,2)(8,1)(9,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,0)(6,1)(7,2)(8,1)(9,1)(10,0)(11,1)(12,2)(13,1)(14,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,0)(6,1)(7,2)(8,1)(9,1)(10,0)(11,1)(12,2)(13,1)(14,1)(15,0)(16,1)(17,2)(18,1)(19,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)(5,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)(5,2)") 1) == "(0,0)(1,1)(2,2)(3,2)(4,2)(5,1)(6,2)(7,2)(8,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)(5,2)") 2) == "(0,0)(1,1)(2,2)(3,2)(4,2)(5,1)(6,2)(7,2)(8,2)(9,1)(10,2)(11,2)(12,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)(5,2)") 3) == "(0,0)(1,1)(2,2)(3,2)(4,2)(5,1)(6,2)(7,2)(8,2)(9,1)(10,2)(11,2)(12,2)(13,1)(14,2)(15,2)(16,2)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)") 1) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,0)(2,1)(3,0)(2,1)(2,1)(2,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)") 2) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,0)(2,1)(3,0)(2,1)(2,1)(2,1)(2,0)(3,1)(4,0)(3,1)(3,1)(3,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)") 3) == "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,0)(2,1)(3,0)(2,1)(2,1)(2,1)(2,0)(3,1)(4,0)(3,1)(3,1)(3,1)(3,0)(4,1)(5,0)(4,1)(4,1)(4,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)") 1) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)") 2) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)") 3) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(3,0)") 1) == "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(2,0)(3,0)(3,0)(3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(3,0)") 2) == "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(2,0)(3,0)(3,0)(3,0)(2,0)(3,0)(3,0)(3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(3,0)") 3) == "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(2,0)(3,0)(3,0)(3,0)(2,0)(3,0)(3,0)(3,0)(2,0)(3,0)(3,0)(3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(4,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(4,0)(5,0)(4,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(4,0)(5,0)(4,0)(5,0)(4,0)(5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)(5,0)(5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,1)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,0)(7,1)(8,2)(9,1)(10,1)(11,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,1)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,0)(7,1)(8,2)(9,1)(10,1)(11,1)(12,0)(13,1)(14,2)(15,1)(16,1)(17,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,1)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,1)(5,1)(6,0)(7,1)(8,2)(9,1)(10,1)(11,1)(12,0)(13,1)(14,2)(15,1)(16,1)(17,1)(18,0)(19,1)(20,2)(21,1)(22,1)(23,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,1)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,0)(7,1)(8,2)(9,1)(10,2)(11,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,1)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,0)(7,1)(8,2)(9,1)(10,2)(11,1)(12,0)(13,1)(14,2)(15,1)(16,2)(17,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,1)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,0)(7,1)(8,2)(9,1)(10,2)(11,1)(12,0)(13,1)(14,2)(15,1)(16,2)(17,1)(18,0)(19,1)(20,2)(21,1)(22,2)(23,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,1)(7,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,1)(7,1)(8,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)") 1) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)") 2) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,2)(8,1)(9,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)") 3) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,2)(8,1)(9,2)(10,1)(11,2)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(0,1,0)(0,1,3)(3,0,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(1,0,0)(1,2,2)(3,1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(1,0,2)(2,1,2)(1,1,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(1,0,2)(2,2,2)(3,3,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,1)(1,2,2)(0,0,0)(3,3,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(0,2,1)(3,0,1)(0,3,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(2,0,1)(1,1,3)(0,1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,0)(0,0,1)(1,3,1)(3,3,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,0)(0,0,2)(2,0,3)(2,2,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,0)(2,1,2)(1,1,0)(0,2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,1)(0,2,1)(0,0,1)(1,1,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,1)(1,0,0)(1,3,1)(0,2,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(0,0,1)(0,1,3)(3,2,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(1,0,1)(0,0,1)(2,2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(1,1,1)(0,1,0)(0,2,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,1,1)(5,2,0)(6,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,1,1)(5,2,0)(6,2,0)(7,1,1)(8,2,0)(9,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,1,1)(5,2,0)(6,2,0)(7,1,1)(8,2,0)(9,2,0)(10,1,1)(11,2,0)(12,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)(8,2,0)(9,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,1)") 1) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,1)") 2) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,1)(8,8,0)(9,9,1)(10,10,1)(11,11,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,1)") 3) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,1)(8,8,0)(9,9,1)(10,10,1)(11,11,1)(12,12,0)(13,13,1)(14,14,1)(15,15,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(2,0)") 1) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(1,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(2,0)") 2) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(1,1)(1,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(2,0)") 3) == "(0,0)(1,1)(2,0)(2,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(4,0)") 1) == "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(3,0)(4,0)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(4,0)") 2) == "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(3,0)(4,0)(4,0)(4,0)(3,0)(4,0)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(4,0)") 3) == "(0,0)(1,1)(2,0)(3,0)(4,0)(4,0)(4,0)(3,0)(4,0)(4,0)(4,0)(3,0)(4,0)(4,0)(4,0)(3,0)(4,0)(4,0)(4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(4,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(3,1)(4,0)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(4,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(3,1)(4,0)(4,0)(4,0)(3,1)(4,0)(4,0)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(4,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(4,0)(3,1)(4,0)(4,0)(4,0)(3,1)(4,0)(4,0)(4,0)(3,1)(4,0)(4,0)(4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)(5,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)(5,0)(6,0)(5,0)(6,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(7,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(7,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(7,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(7,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(6,0)(6,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(6,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(6,0)(6,0)(6,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,1)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,1)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(8,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,1)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(8,0)(9,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,1)") 1) == "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,0)(8,1)(9,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,1)") 2) == "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,0)(8,1)(9,1)(10,0)(11,1)(12,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,1)") 3) == "(0,0)(1,1)(2,1)(3,1)(4,0)(5,1)(6,1)(7,0)(8,1)(9,1)(10,0)(11,1)(12,1)(13,0)(14,1)(15,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,1)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,0)(8,1)(9,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,1)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,0)(8,1)(9,2)(10,0)(11,1)(12,2)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,1)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,0)(5,1)(6,2)(7,0)(8,1)(9,2)(10,0)(11,1)(12,2)(13,0)(14,1)(15,2)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,1)") 1) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,0)(8,1)(9,2)(10,2)(11,1)(12,2)(13,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,1)") 2) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,0)(8,1)(9,2)(10,2)(11,1)(12,2)(13,1)(14,0)(15,1)(16,2)(17,2)(18,1)(19,2)(20,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,1)") 3) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,0)(8,1)(9,2)(10,2)(11,1)(12,2)(13,1)(14,0)(15,1)(16,2)(17,2)(18,1)(19,2)(20,1)(21,0)(22,1)(23,2)(24,2)(25,1)(26,2)(27,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,2)") 1) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,2)") 2) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,1)(8,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,2)") 3) == "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,1)(7,1)(8,1)(9,1)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(0,2,1)(0,3,1)(0,3,2)(3,2,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(2,1,1)(3,2,0)(1,2,2)(0,2,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,0,0)(2,2,1)(1,1,2)(3,3,1)(1,0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(0,0,1)(1,3,3)(2,2,3)(0,3,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(0,1,1)(1,2,1)(3,3,1)(1,2,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,0)(0,2,0)(0,1,1)(1,3,2)(0,0,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,1)(1,0,0)(0,2,1)(3,2,0)(3,0,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(0,1,1)(1,0,1)(3,2,1)(3,3,2)(1,1,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,0)(1,2,2)(3,3,1)(3,1,3)(3,1,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,0)(2,0,0)(0,2,3)(2,2,0)(3,2,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,0,1)(1,1,2)(0,0,0)(0,2,0)(3,0,0)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(0,2,2)(2,3,3)(3,3,1)(0,1,1)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,0)(1,0,0)(1,3,3)(1,0,3)(1,1,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(1,2,1)(1,0,1)(0,1,1)(0,3,3)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,1,0)(3,2,2)(1,3,3)(0,1,2)") == false
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,2,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,1,1)(6,2,0)(7,2,0)(8,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,2,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,1,1)(6,2,0)(7,2,0)(8,2,0)(9,1,1)(10,2,0)(11,2,0)(12,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,2,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,1,1)(6,2,0)(7,2,0)(8,2,0)(9,1,1)(10,2,0)(11,2,0)(12,2,0)(13,1,1)(14,2,0)(15,2,0)(16,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,1,1)(6,2,0)(7,3,0)(8,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,1,1)(6,2,0)(7,3,0)(8,2,0)(9,1,1)(10,2,0)(11,3,0)(12,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,1,1)(6,2,0)(7,3,0)(8,2,0)(9,1,1)(10,2,0)(11,3,0)(12,2,0)(13,1,1)(14,2,0)(15,3,0)(16,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,2,0)(7,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,3,0)(8,2,0)(9,3,0)(10,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,3,0)(8,2,0)(9,3,0)(10,3,0)(11,2,0)(12,3,0)(13,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,4,0)(9,3,0)(10,4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,5,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,5,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,5,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,4,0)(6,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,4,0)(6,4,0)(7,4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,7,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)") 1) == "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(1,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)") 2) == "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(1,1)(1,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)") 3) == "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)") 1) == "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)") 2) == "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(2,0)") 3) == "(0,0)(1,1)(2,0)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)(1,1)(2,0)(2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(3,1)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(3,1)(4,0)(3,1)(4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(4,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)(3,1)(4,0)(3,1)(4,0)(3,1)(4,0)(3,1)(4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(5,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(4,0)(5,0)(6,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(5,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(4,0)(5,0)(6,0)(5,0)(4,0)(5,0)(6,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(5,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(4,0)(5,0)(6,0)(5,0)(4,0)(5,0)(6,0)(5,0)(4,0)(5,0)(6,0)(5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(5,0)(5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(5,0)(5,0)(5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(6,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(5,0)(6,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(6,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(5,0)(6,0)(6,0)(5,0)(6,0)(6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(6,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(5,0)(6,0)(6,0)(5,0)(6,0)(6,0)(5,0)(6,0)(6,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(8,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(8,0)") 1) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(7,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(8,0)") 2) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(7,0)(7,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(8,0)") 3) == "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)(7,0)(7,0)(7,0)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,1)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,0)(9,1)(10,2)(11,1)(12,2)(13,1)(14,2)(15,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,1)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,0)(9,1)(10,2)(11,1)(12,2)(13,1)(14,2)(15,1)(16,0)(17,1)(18,2)(19,1)(20,2)(21,1)(22,2)(23,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,1)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,0)(9,1)(10,2)(11,1)(12,2)(13,1)(14,2)(15,1)(16,0)(17,1)(18,2)(19,1)(20,2)(21,1)(22,2)(23,1)(24,0)(25,1)(26,2)(27,1)(28,2)(29,1)(30,2)(31,1)"
#guard Bms.isStandard (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,2)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,2)") 1) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,2)") 2) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,1)(9,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,2)") 3) == "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,1)(9,1)(10,1)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,2,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,1,1)(7,2,0)(8,3,0)(9,2,0)(10,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,2,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,1,1)(7,2,0)(8,3,0)(9,2,0)(10,2,0)(11,1,1)(12,2,0)(13,3,0)(14,2,0)(15,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,2,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,2,0)(6,1,1)(7,2,0)(8,3,0)(9,2,0)(10,2,0)(11,1,1)(12,2,0)(13,3,0)(14,2,0)(15,2,0)(16,1,1)(17,2,0)(18,3,0)(19,2,0)(20,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,2,0)(7,3,0)(8,3,0)(9,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,2,0)(7,3,0)(8,3,0)(9,3,0)(10,2,0)(11,3,0)(12,3,0)(13,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,2,0)(7,3,0)(8,3,0)(9,3,0)(10,2,0)(11,3,0)(12,3,0)(13,3,0)(14,2,0)(15,3,0)(16,3,0)(17,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,2,0)(7,3,0)(8,4,0)(9,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,2,0)(7,3,0)(8,4,0)(9,3,0)(10,2,0)(11,3,0)(12,4,0)(13,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,2,0)(7,3,0)(8,4,0)(9,3,0)(10,2,0)(11,3,0)(12,4,0)(13,3,0)(14,2,0)(15,3,0)(16,4,0)(17,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,3,0)(7,4,0)(8,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,3,0)(7,4,0)(8,4,0)(9,3,0)(10,4,0)(11,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,3,0)(7,4,0)(8,4,0)(9,3,0)(10,4,0)(11,4,0)(12,3,0)(13,4,0)(14,4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,4,0)(7,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,4,0)(7,5,0)(8,4,0)(9,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,4,0)(7,5,0)(8,4,0)(9,5,0)(10,4,0)(11,5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,2,0)(9,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,3,0)(9,2,0)(10,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,3,0)(9,2,0)(10,3,0)(11,2,0)(12,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,2,0)(8,3,0)(9,4,0)(10,3,0)(11,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,2,0)(8,3,0)(9,4,0)(10,3,0)(11,3,0)(12,2,0)(13,3,0)(14,4,0)(15,3,0)(16,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,2,0)(8,3,0)(9,4,0)(10,3,0)(11,3,0)(12,2,0)(13,3,0)(14,4,0)(15,3,0)(16,3,0)(17,2,0)(18,3,0)(19,4,0)(20,3,0)(21,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,4,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,3,0)(8,4,0)(9,4,0)(10,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,4,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,3,0)(8,4,0)(9,4,0)(10,4,0)(11,3,0)(12,4,0)(13,4,0)(14,4,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,4,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)(7,3,0)(8,4,0)(9,4,0)(10,4,0)(11,3,0)(12,4,0)(13,4,0)(14,4,0)(15,3,0)(16,4,0)(17,4,0)(18,4,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,6,0)(9,5,0)(10,6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,6,0)(9,5,0)(10,6,0)(11,5,0)(12,6,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,7,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,7,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,7,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,7,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,6,0)(9,6,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,1)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,1)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,0)(8,8,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,1)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,1)(6,6,0)(7,7,0)(8,8,0)(9,9,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,1)") 1) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,0)(8,8,1)(9,9,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,1)") 2) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,0)(8,8,1)(9,9,1)(10,10,0)(11,11,1)(12,12,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,1)") 3) == "(0,0,0)(1,1,1)(2,2,1)(3,3,1)(4,4,0)(5,5,1)(6,6,1)(7,7,0)(8,8,1)(9,9,1)(10,10,0)(11,11,1)(12,12,1)(13,13,0)(14,14,1)(15,15,1)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,2,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,2,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,1,1)(9,2,0)(10,3,0)(11,2,0)(12,3,0)(13,2,0)(14,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,2,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,1,1)(9,2,0)(10,3,0)(11,2,0)(12,3,0)(13,2,0)(14,2,0)(15,1,1)(16,2,0)(17,3,0)(18,2,0)(19,3,0)(20,2,0)(21,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,2,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,2,0)(8,1,1)(9,2,0)(10,3,0)(11,2,0)(12,3,0)(13,2,0)(14,2,0)(15,1,1)(16,2,0)(17,3,0)(18,2,0)(19,3,0)(20,2,0)(21,2,0)(22,1,1)(23,2,0)(24,3,0)(25,2,0)(26,3,0)(27,2,0)(28,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,2,0)(9,2,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,2,0)(6,3,0)(7,2,0)(8,2,0)(9,2,0)(10,2,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,2,0)(9,3,0)(10,4,0)(11,3,0)(12,3,0)(13,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,2,0)(9,3,0)(10,4,0)(11,3,0)(12,3,0)(13,3,0)(14,2,0)(15,3,0)(16,4,0)(17,3,0)(18,3,0)(19,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,3,0)(7,3,0)(8,2,0)(9,3,0)(10,4,0)(11,3,0)(12,3,0)(13,3,0)(14,2,0)(15,3,0)(16,4,0)(17,3,0)(18,3,0)(19,3,0)(20,2,0)(21,3,0)(22,4,0)(23,3,0)(24,3,0)(25,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,3,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,3,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,2,0)(9,3,0)(10,4,0)(11,3,0)(12,4,0)(13,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,3,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,2,0)(9,3,0)(10,4,0)(11,3,0)(12,4,0)(13,3,0)(14,2,0)(15,3,0)(16,4,0)(17,3,0)(18,4,0)(19,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,3,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,2,0)(9,3,0)(10,4,0)(11,3,0)(12,4,0)(13,3,0)(14,2,0)(15,3,0)(16,4,0)(17,3,0)(18,4,0)(19,3,0)(20,2,0)(21,3,0)(22,4,0)(23,3,0)(24,4,0)(25,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,4,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,4,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,4,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,3,0)(9,3,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,4,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,3,0)(9,3,0)(10,3,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,5,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,4,0)(9,5,0)(10,5,0)(11,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,5,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,4,0)(9,5,0)(10,5,0)(11,5,0)(12,4,0)(13,5,0)(14,5,0)(15,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,5,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,5,0)(7,5,0)(8,4,0)(9,5,0)(10,5,0)(11,5,0)(12,4,0)(13,5,0)(14,5,0)(15,5,0)(16,4,0)(17,5,0)(18,5,0)(19,5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,5,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,5,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,4,0)(9,5,0)(10,6,0)(11,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,5,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,4,0)(9,5,0)(10,6,0)(11,5,0)(12,4,0)(13,5,0)(14,6,0)(15,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,5,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,4,0)(9,5,0)(10,6,0)(11,5,0)(12,4,0)(13,5,0)(14,6,0)(15,5,0)(16,4,0)(17,5,0)(18,6,0)(19,5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,6,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,6,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,5,0)(9,5,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,6,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,5,0)(8,5,0)(9,5,0)(10,5,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,6,0)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,6,0)") 1) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,5,0)(9,6,0)(10,6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,6,0)") 2) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,5,0)(9,6,0)(10,6,0)(11,5,0)(12,6,0)(13,6,0)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,6,0)") 3) == "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,5,0)(9,6,0)(10,6,0)(11,5,0)(12,6,0)(13,6,0)(14,5,0)(15,6,0)(16,6,0)"
#guard Bms.isStandard (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,1)") == true
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,1)") 1) == "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,0)(9,9,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,1)") 2) == "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,0)(9,9,1)(10,10,0)(11,11,1)"
#guard Bms.toString (Bms.expand (Bms.parse! "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,1)") 3) == "(0,0,0)(1,1,1)(2,2,1)(3,3,0)(4,4,1)(5,5,1)(6,6,0)(7,7,1)(8,8,0)(9,9,1)(10,10,0)(11,11,1)(12,12,0)(13,13,1)"
#guard Bms.compare (Bms.parse! "(0,0,0)(0,1,0)(1,0,2)(3,2,2)") (Bms.parse! "(0,0,0)(0,0,1)(1,2,2)(0,0,0)(3,3,0)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,1,0)(3,2,2)(1,3,3)(0,1,2)") (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,2,0)(4,2,0)(5,2,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,0)(1,2,1)(0,0,3)") (Bms.parse! "(0,0,0)(0,0,0)(1,1,1)") == .gt
#guard Bms.compare (Bms.parse! "(0)(1)(0)") (Bms.parse! "(0)(1)(1)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)") (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)(6,0)(7,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(4,0)") (Bms.parse! "(0,0)(1,0)(2,0)(0,1)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,1,0)(3,2,2)(1,3,3)(0,1,2)") (Bms.parse! "(0,0,0)(0,1,1)(2,1,2)(2,2,2)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(1,0)(0,0)(1,0)(2,0)(2,0)") (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(1,0)(1,1)") (Bms.parse! "(0,0)(0,0)(0,0)(1,0)(1,0)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(1,0)(1,1)") (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)") (Bms.parse! "(0,0,0)(0,1,1)(2,2,1)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(0,0,0)(0,2,1)(0,2,3)") (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,3,0)(5,3,0)(6,3,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)(7,6,0)(8,6,0)") (Bms.parse! "(0,0,0)(1,1,1)(1,0,1)(0,0,1)(2,2,0)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,0,1)(0,2,1)(0,0,1)(1,1,0)") (Bms.parse! "(0,0,0)(0,1,0)(0,1,1)(1,2,1)(3,3,1)(1,2,3)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)") (Bms.parse! "(0,0,0)(1,0,0)(0,0,2)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(0,1,0)(0,0,1)(1,3,3)(2,2,3)(0,3,3)") (Bms.parse! "(0,0,0)(0,0,0)(2,1,1)(3,2,0)(1,2,2)(0,2,2)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(1,0)(2,2)(0,1)(1,1)(3,3)") (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)(5,1)(6,2)(7,1)(8,2)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,1)(3,1)(3,0)") (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,1)(5,2)(6,2)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(0,1)(0,0)(1,1)(1,0)(2,0)") (Bms.parse! "(0,0)(1,1)(2,0)(3,1)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(0,1)(1,2)(1,1)(3,1)") (Bms.parse! "(0,0)(1,1)(2,2)(3,2)(4,2)(5,2)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(0,0,0)") (Bms.parse! "(0,0,0)(0,1,1)(2,1,2)(2,2,2)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,2)") (Bms.parse! "(0,0)(1,1)(2,0)(2,0)(2,0)(2,0)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(1,0)(2,0)(0,3)(1,0)") (Bms.parse! "(0,0)(0,1)(2,1)(2,1)(2,3)(0,1)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(0,0)(1,2)(1,0)(1,0)(2,0)") (Bms.parse! "(0,0)(1,1)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)(6,4,0)") (Bms.parse! "(0,0,0)(0,1,0)(2,0,1)(1,1,3)(0,1,0)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(1,0)(1,1)") (Bms.parse! "(0,0)(1,1)(2,2)(3,1)(4,2)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(0,3)(1,1)(0,0)") (Bms.parse! "(0,0)(0,0)(0,0)(1,0)(1,0)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,3,0)(6,4,0)(7,3,0)(8,4,0)") (Bms.parse! "(0,0,0)(0,0,0)(1,1,1)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(0,0,1)(1,2,2)(0,0,0)(3,3,0)") (Bms.parse! "(0,0,0)(0,1,0)(0,2,0)(0,1,1)(1,3,2)(0,0,3)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,4,0)") (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,1)(4,4,0)(5,5,0)(6,6,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(3,0)(3,0)(3,0)(3,0)") (Bms.parse! "(0,0)(0,1)(0,1)(0,1)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(0,1)(1,2)(1,1)(3,1)") (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(5,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)") (Bms.parse! "(0,0)(0,0)(1,2)(2,2)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(0,1)(1,2)(2,1)(1,1)(0,3)") (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(5,0)(6,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,1)") (Bms.parse! "(0,0)(1,1)(2,1)(3,2)(0,1)(3,1)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,0,0)(0,0,2)(2,0,3)(2,2,1)") (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,4,0)(5,5,0)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)") (Bms.parse! "(0,0,0)(0,0,0)(1,0,2)(2,1,2)(1,1,2)") == .gt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,1)(2,2,0)(3,3,0)(4,2,0)(5,3,0)(6,2,0)(7,3,0)") (Bms.parse! "(0,0,0)(0,1,0)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)(1,1)(2,0)") (Bms.parse! "(0,0)(1,1)(2,0)(1,1)(1,1)(1,1)(1,1)") == .gt
#guard Bms.compare (Bms.parse! "(0,0)(1,1)(2,0)(3,1)(4,0)(5,0)(6,0)(6,0)(6,0)") (Bms.parse! "(0,0)(1,1)(2,2)(3,3)") == .lt
#guard Bms.compare (Bms.parse! "(0,0,0)(1,1,0)(1,0,0)(1,3,3)(1,0,3)(1,1,2)") (Bms.parse! "(0,0,0)(0,0,1)(2,1,0)") == .gt
